"use client";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import {
  Calendar,
  CheckCircle2,
  Medal,
  Pencil,
  Trophy,
  Trash2,
} from "lucide-react";
import { formatDate } from "@/lib/formatters";

function renderLink(link) {
  if (!link) return null;
  return (
    <a
      href={link}
      target="_blank"
      rel="noopener noreferrer"
      className="inline-flex items-center text-[11px] font-semibold text-slate-600 underline hover:text-slate-900"
    >
      Lihat berkas
    </a>
  );
}

export function JuaraTable({
  items,
  loading,
  canEdit,
  onEdit,
  onDelete,
  onConfirmAuto,
  confirmingId,
  startIndex = 1,
}) {
  const hasData = items && items.length > 0;

  if (loading) {
    return (
      <div className="px-3 sm:px-4 py-4">
        <TableSkeleton />
      </div>
    );
  }

  if (!hasData) {
    return (
      <div className="px-4 py-8 text-center text-sm text-slate-500">
        Belum ada data juara. Tambahkan hasil lomba untuk setiap event.
      </div>
    );
  }

  return (
    <div className="w-full">
      {/* mobile cards */}
      <div className="space-y-3 px-3 py-3 sm:hidden">
        {items.map((entry, idx) => (
          <div
            key={entry.id}
            className="flex flex-col gap-2 rounded-xl border border-slate-200 bg-white p-3 text-sm shadow-sm transition-all hover:-translate-y-[1px] hover:shadow-md"
          >
            <div className="flex items-start justify-between gap-2">
              <div className="space-y-0.5">
                <p className="text-base font-semibold text-slate-900">
                  {entry.peserta?.namaTim || "Tim tidak diketahui"}
                </p>
                <p className="text-xs text-slate-500">
                  {entry.event?.namaEvent || "Event tidak diketahui"}
                </p>
              </div>
              <div className="flex flex-col items-end gap-1 text-right">
                <span className="text-[11px] font-semibold text-slate-400">
                  No. {startIndex + idx}
                </span>
                <span className="inline-flex items-center gap-1 rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-[11px] font-semibold text-amber-700">
                  <Trophy className="h-3.5 w-3.5" />
                  {entry.juara}
                </span>
              </div>
            </div>
            {entry.kategori && (
              <span className="inline-flex items-center gap-1 text-xs text-slate-500">
                <Medal className="h-3.5 w-3.5" />
                {entry.kategori}
              </span>
            )}
            {entry.autoGenerated && (
              <p className="text-[11px] text-amber-600">
                Ranking otomatis dari nilai (nilai {entry.nilai || 0})
              </p>
            )}
            <div className="flex items-center gap-1 text-xs text-slate-500">
              <Calendar className="h-3.5 w-3.5" />
              <span>{formatDate(entry.event?.tanggalEvent)}</span>
            </div>
            {entry.berkasLink && renderLink(entry.berkasLink)}

            {canEdit && (
              <div className="flex justify-end gap-2 pt-1">
                {entry.autoGenerated && onConfirmAuto && (
                  <Button
                    size="sm"
                    variant="outline"
                    className="h-8 rounded-full border-amber-200 text-amber-800 hover:bg-amber-50"
                    disabled={confirmingId === entry.id}
                    onClick={() => onConfirmAuto(entry)}
                  >
                    <CheckCircle2 className="mr-1 h-3.5 w-3.5" />
                    {confirmingId === entry.id
                      ? "Menyimpan..."
                      : "Konfirmasi penilaian"}
                  </Button>
                )}
                {!entry.autoGenerated && (
                  <Button
                    size="icon"
                    variant="dark"
                    className="h-7 w-7 rounded-full"
                    aria-label={`Edit juara ${entry.peserta?.namaTim}`}
                    onClick={() => onEdit?.(entry)}
                  >
                    <Pencil className="h-3 w-3" />
                  </Button>
                )}
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      size="icon"
                      variant="dark"
                      className="h-7 w-7 rounded-full"
                      aria-label={`Hapus juara ${entry.peserta?.namaTim}`}
                    >
                      <Trash2 className="h-3 w-3" />
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent className="rounded-xl border border-slate-200 bg-white">
                    <AlertDialogHeader>
                      <AlertDialogTitle>
                        {entry.autoGenerated
                          ? "Hapus penilaian otomatis?"
                          : "Hapus data juara?"}
                      </AlertDialogTitle>
                      <AlertDialogDescription className="text-sm text-slate-600">
                        {entry.autoGenerated ? (
                          <>
                            Seluruh score untuk tim {entry.peserta?.namaTim || "Tanpa nama"}
                            {" "}
                            pada event ini akan dihapus dan ranking otomatis
                            hilang.
                          </>
                        ) : (
                          <>
                            Status juara dan seluruh score tim {" "}
                            <b>{entry.peserta?.namaTim || "Tanpa nama"}</b> di event ini akan dihapus.
                          </>
                        )}
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Batal</AlertDialogCancel>
                      <AlertDialogAction
                        className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                        onClick={() => onDelete?.(entry)}
                      >
                        {entry.autoGenerated ? "Ya, hapus penilaian" : "Ya, hapus"}
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* desktop table */}
      <div className="hidden sm:block">
        <div className="w-full overflow-x-auto py-1">
          <Table className="w-full whitespace-nowrap">
            <TableHeader>
              <TableRow className="border-b bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
                <TableHead className="w-[5%] px-4 py-3 text-center">No</TableHead>
                <TableHead className="w-[26%] px-4 py-3">Event</TableHead>
                <TableHead className="w-[26%] px-4 py-3">Tim</TableHead>
                <TableHead className="w-[16%] px-4 py-3 text-center">
                  Juara
                </TableHead>
                <TableHead className="w-[16%] px-4 py-3">Kriteria</TableHead>
                <TableHead className="w-[10%] px-4 py-3 text-center">
                  Berkas
                </TableHead>
                <TableHead className="w-[10%] px-4 py-3 text-center">
                  Set oleh
                </TableHead>
                {canEdit && (
                  <TableHead className="w-[6%] px-4 py-3 text-center">
                    Aksi
                  </TableHead>
                )}
              </TableRow>
            </TableHeader>
            <TableBody className="divide-y divide-slate-100 bg-white">
              {items.map((entry, idx) => (
                <TableRow
                  key={entry.id}
                  className="text-sm text-slate-700 transition-colors hover:bg-slate-50"
                >
                  <TableCell className="px-4 py-3 text-center text-xs font-semibold text-slate-500">
                    {startIndex + idx}
                  </TableCell>
                  <TableCell className="px-4 py-3 align-top">
                    <p className="font-semibold text-slate-900">
                      {entry.event?.namaEvent || "Event tidak diketahui"}
                    </p>
                    <p className="text-xs text-slate-500">
                      {formatDate(entry.event?.tanggalEvent)}
                    </p>
                  </TableCell>
                  <TableCell className="px-4 py-3 align-top">
                    <p className="font-medium text-slate-900">
                      {entry.peserta?.namaTim || "Tim tidak diketahui"}
                    </p>
                    <p className="text-xs text-slate-500">
                      {entry.peserta?.namaPerwakilan || "-"}
                    </p>
                  </TableCell>
                  <TableCell className="px-4 py-3 align-top text-center">
                    <span className="inline-flex items-center gap-1 rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">
                      <Trophy className="h-3.5 w-3.5" />
                      {entry.juara}
                    </span>
                  </TableCell>
                  <TableCell className="px-4 py-3 align-top text-xs text-slate-600">
                    {entry.kategori || "-"}
                  </TableCell>
                  <TableCell className="px-4 py-3 align-top text-center text-xs text-slate-500">
                    {entry.berkasLink ? (
                      <a
                        href={entry.berkasLink}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-slate-600 underline hover:text-slate-900"
                      >
                        Berkas
                      </a>
                    ) : entry.autoGenerated ? (
                      "-"
                    ) : (
                      "-"
                    )}
                    {entry.autoGenerated && (
                      <p className="mt-1 text-[10px] text-amber-600">
                        Otomatis (nilai {entry.nilai || 0})
                      </p>
                    )}
                  </TableCell>
                  <TableCell className="px-4 py-3 align-top text-center text-xs text-slate-500">
                    {entry.setByUser?.username || entry.setByUser?.email || "-"}
                  </TableCell>
                {canEdit && (
                  <TableCell className="px-4 py-3 align-top text-center">
                    <div className="flex justify-center gap-2">
                      {entry.autoGenerated && onConfirmAuto && (
                        <Button
                          size="xs"
                          variant="outline"
                          className="rounded-full border-amber-200 text-amber-800 hover:bg-amber-50"
                          disabled={confirmingId === entry.id}
                          onClick={() => onConfirmAuto(entry)}
                        >
                          <CheckCircle2 className="mr-1 h-3 w-3" />
                          {confirmingId === entry.id
                            ? "Menyimpan..."
                            : "Konfirmasi"}
                        </Button>
                      )}
                      {!entry.autoGenerated && (
                        <Button
                          size="icon"
                            variant="dark"
                            className="h-8 w-8 rounded-full"
                            aria-label={`Edit juara ${entry.peserta?.namaTim}`}
                            onClick={() => onEdit?.(entry)}
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                        )}
                        <AlertDialog>
                          <AlertDialogTrigger asChild>
                            <Button
                              size="icon"
                              variant="dark"
                              className="h-8 w-8 rounded-full"
                              aria-label={`Hapus juara ${entry.peserta?.namaTim}`}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </AlertDialogTrigger>
                          <AlertDialogContent className="rounded-xl border border-slate-200 bg-white">
                            <AlertDialogHeader>
                              <AlertDialogTitle>
                                {entry.autoGenerated
                                  ? "Hapus penilaian otomatis?"
                                  : "Hapus data juara?"}
                              </AlertDialogTitle>
                              <AlertDialogDescription className="text-sm text-slate-600">
                                {entry.autoGenerated ? (
                                  <>
                                    Seluruh score untuk tim {entry.peserta?.namaTim || "Tanpa nama"}
                                    {" "}
                                    pada event ini akan dihapus dan ranking
                                    otomatis hilang.
                                  </>
                                ) : (
                                  <>
                                    Status juara dan score tim ini akan
                                    dibersihkan dari event terkait.
                                  </>
                                )}
                              </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                              <AlertDialogCancel>Batal</AlertDialogCancel>
                              <AlertDialogAction
                                className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                                onClick={() => onDelete?.(entry)}
                              >
                                {entry.autoGenerated
                                  ? "Ya, hapus penilaian"
                                  : "Ya, hapus"}
                              </AlertDialogAction>
                            </AlertDialogFooter>
                          </AlertDialogContent>
                        </AlertDialog>
                      </div>
                    </TableCell>
                  )}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  );
}

function TableSkeleton() {
  const rows = Array.from({ length: 4 });
  return (
    <div className="space-y-4">
      <div className="sm:hidden space-y-3">
        {rows.map((_, idx) => (
          <div
            key={`mobile-skeleton-${idx}`}
            className="rounded-xl border border-slate-100 bg-slate-50 p-3 space-y-2"
          >
            <div className="h-4 w-2/3 rounded bg-slate-200" />
            <div className="h-3 w-1/2 rounded bg-slate-200" />
            <div className="h-3 w-1/3 rounded bg-slate-200" />
          </div>
        ))}
      </div>

      <div className="hidden w-full overflow-x-auto sm:block">
        <table className="w-full">
          <tbody className="divide-y divide-slate-100">
            {rows.map((_, idx) => (
              <tr key={`desktop-skeleton-${idx}`} className="animate-pulse">
                {Array.from({ length: 6 }).map((__, colIdx) => (
                  <td key={colIdx} className="px-4 py-3">
                    <div className="h-4 rounded bg-slate-200" />
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
